### ISSUE TITLE
add rss feed

### ISSUE THREAD

**Issue by foldfree** [sergiobarriel/tophat-theme#2]
I don't know if you forgot or there is a reason this file was left blank?

in `/layouts/partials/head.html` add:
```
{{ with .OutputFormats.Get "rss" -}}
  {{ printf `<link rel=%q type=%q href=%q title=%q>` .Rel .MediaType.Type .Permalink site.Title | safeHTML }}
{{ end }}
```

This create an example.com/index.xml so people can subscribe to your blog with their favorite rss clients.

**Comment by sergiobarriel** [comment]
Hi @foldfree 

It hasn't been intentional, I probably forgot. 

I'll also plan this feature.

Thanks 🙂

**Comment by sergiobarriel** [comment]
Hi @foldfree,

I have incorporated the suggested content into the **head.html** template, and as a result, I am pleased to inform you that the RSS feed, located at https://www.nohat.dev/index.xml now complies with the W3C feed validation standards. You can verify its validity using the W3C feed validator tool.

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.nohat.dev%2Findex.xml

Thank you for your valuable input and assistance.
